-- Phonnapa Studio: services price + 30-day schedule admin
create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.services (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  price text not null,
  sort_order integer not null default 0,
  active boolean not null default true,
  updated_at timestamptz not null default now()
);

create table if not exists public.schedule_slots (
  id bigint generated by default as identity primary key,
  slot_date date not null,
  slot_time time not null,
  status text not null default 'booked' check (status in ('available', 'booked', 'holiday')),
  updated_at timestamptz not null default now(),
  unique (slot_date, slot_time)
);

create table if not exists public.schedule_slot_notes (
  slot_id bigint primary key references public.schedule_slots(id) on delete cascade,
  customer_name text not null default '',
  updated_at timestamptz not null default now()
);

create table if not exists public.promotions (
  id bigint generated by default as identity primary key,
  title text not null default '',
  image_url text not null,
  storage_path text not null unique,
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.admin_users enable row level security;
alter table public.services enable row level security;
alter table public.schedule_slots enable row level security;
alter table public.schedule_slot_notes enable row level security;
alter table public.promotions enable row level security;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.admin_users where user_id = auth.uid()
  );
$$;

drop policy if exists "Admin can view own membership" on public.admin_users;
create policy "Admin can view own membership" on public.admin_users
  for select to authenticated using (user_id = auth.uid());

drop policy if exists "Public can read active services" on public.services;
create policy "Public can read active services" on public.services
  for select to anon, authenticated using (active = true or public.is_admin());
drop policy if exists "Admin can update services" on public.services;
create policy "Admin can update services" on public.services
  for update to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Public can read schedule" on public.schedule_slots;
create policy "Public can read schedule" on public.schedule_slots
  for select to anon, authenticated using (true);
drop policy if exists "Admin can insert schedule" on public.schedule_slots;
create policy "Admin can insert schedule" on public.schedule_slots
  for insert to authenticated with check (public.is_admin());
drop policy if exists "Admin can update schedule" on public.schedule_slots;
create policy "Admin can update schedule" on public.schedule_slots
  for update to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists "Admin can delete schedule" on public.schedule_slots;
create policy "Admin can delete schedule" on public.schedule_slots
  for delete to authenticated using (public.is_admin());

drop policy if exists "Admin can read schedule notes" on public.schedule_slot_notes;
create policy "Admin can read schedule notes" on public.schedule_slot_notes
  for select to authenticated using (public.is_admin());
drop policy if exists "Admin can insert schedule notes" on public.schedule_slot_notes;
create policy "Admin can insert schedule notes" on public.schedule_slot_notes
  for insert to authenticated with check (public.is_admin());
drop policy if exists "Admin can update schedule notes" on public.schedule_slot_notes;
create policy "Admin can update schedule notes" on public.schedule_slot_notes
  for update to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists "Admin can delete schedule notes" on public.schedule_slot_notes;
create policy "Admin can delete schedule notes" on public.schedule_slot_notes
  for delete to authenticated using (public.is_admin());
drop policy if exists "Public can read customer names" on public.schedule_slot_notes;
create policy "Public can read customer names" on public.schedule_slot_notes
  for select to anon, authenticated using (true);

drop policy if exists "Public can read active promotions" on public.promotions;
create policy "Public can read active promotions" on public.promotions
  for select to anon, authenticated using (active = true or public.is_admin());
drop policy if exists "Admin can insert promotions" on public.promotions;
create policy "Admin can insert promotions" on public.promotions
  for insert to authenticated with check (public.is_admin());
drop policy if exists "Admin can update promotions" on public.promotions;
create policy "Admin can update promotions" on public.promotions
  for update to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists "Admin can delete promotions" on public.promotions;
create policy "Admin can delete promotions" on public.promotions
  for delete to authenticated using (public.is_admin());

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('promotions', 'promotions', true, 6291456, array['image/jpeg','image/png','image/webp','image/gif'])
on conflict (id) do update set public = true, file_size_limit = 6291456,
  allowed_mime_types = array['image/jpeg','image/png','image/webp','image/gif'];

drop policy if exists "Public can view promotion images" on storage.objects;
create policy "Public can view promotion images" on storage.objects
  for select to anon, authenticated using (bucket_id = 'promotions');
drop policy if exists "Admin can upload promotion images" on storage.objects;
create policy "Admin can upload promotion images" on storage.objects
  for insert to authenticated with check (bucket_id = 'promotions' and public.is_admin());
drop policy if exists "Admin can update promotion images" on storage.objects;
create policy "Admin can update promotion images" on storage.objects
  for update to authenticated using (bucket_id = 'promotions' and public.is_admin());
drop policy if exists "Admin can delete promotion images" on storage.objects;
create policy "Admin can delete promotion images" on storage.objects
  for delete to authenticated using (bucket_id = 'promotions' and public.is_admin());

insert into public.services (slug, name, price, sort_order) values
  ('solid-gel', 'ทาเจลสีพื้น', '159 – 189 บาท', 1),
  ('glitter-gel', 'ทาเจลกลิตเตอร์', '189 – 199 บาท', 2),
  ('cat-eye-gel', 'ทาเจลลูกแก้ว / สีผง', '199 – 229 บาท', 3),
  ('nail-charms', 'งานฝังอะไหล่', 'เริ่มต้น 10 บาท/นิ้ว', 4),
  ('nail-art', 'งานเพ้นท์', 'เริ่มต้น 10 บาท/นิ้ว', 5),
  ('sculpted-art', 'งานปั้นนูน', 'เริ่มต้น 10 บาท/นิ้ว', 6),
  ('overlay', 'เสริมหน้าเล็บ', '59 บาท', 7),
  ('pvc-extension', 'ต่อเล็บ PVC (กาวเจล)', '129 บาท', 8),
  ('pvc-extension-promo', 'ต่อเล็บ PVC (เจนโคนกาวเจล) — ราคาโปร', '159 บาท', 9),
  ('extension-removal', 'ถอดเล็บ PVC / เจลเสริม', '119 บาท', 10),
  ('extension-removal-shop', 'ถอดเล็บ PVC / เจลเสริม เมื่อทำจากที่ร้าน', '69 บาท', 11),
  ('gel-removal', 'ล้างสีเจลโดยเครื่องเจีย', '39 บาท', 12),
  ('gel-removal-shop', 'ล้างสีเจลโดยเครื่องเจีย เมื่อทำจากที่ร้าน', 'ฟรี', 13),
  ('gel-removal-soak', 'ล้างสีเจลโดยเครื่องเจีย + น้ำยา', '59 บาท', 14),
  ('cuticle-remove', 'CUTICLE REMOVE', '139 – 239 บาท', 15),
  ('mini-hand-spa', 'MINI HAND SPA 5 ขั้นตอน', '189 บาท', 16),
  ('mini-foot-spa', 'MINI FOOT SPA 6 ขั้นตอน', '289 บาท', 17),
  ('lash-lift', 'ลิฟต์ขนตา', '259 บาท', 18),
  ('brow-lift', 'ลิฟต์ขนคิ้ว', '89 บาท', 19)
on conflict (slug) do update set
  name = excluded.name,
  sort_order = excluded.sort_order;

-- หลังสร้างผู้ใช้ใน Authentication > Users แล้ว ให้รันคำสั่งนี้โดยแทน EMAIL:
-- insert into public.admin_users (user_id)
-- select id from auth.users where email = 'YOUR_ADMIN_EMAIL';
