-- Run this only when 001_admin.sql was already applied before the expanded admin update.
alter table public.schedule_slots add column if not exists id bigint generated by default as identity;
alter table public.schedule_slots drop constraint if exists schedule_slots_pkey;
alter table public.schedule_slots add constraint schedule_slots_pkey primary key (id);
create unique index if not exists schedule_slots_date_time_key on public.schedule_slots(slot_date, slot_time);

create table if not exists public.schedule_slot_notes (
  slot_id bigint primary key references public.schedule_slots(id) on delete cascade,
  customer_name text not null default '', note text not null default '', updated_at timestamptz not null default now()
);
create table if not exists public.promotions (
  id bigint generated by default as identity primary key,
  title text not null default '', image_url text not null, storage_path text not null unique,
  active boolean not null default true, sort_order integer not null default 0, created_at timestamptz not null default now()
);
alter table public.schedule_slot_notes enable row level security;
alter table public.promotions enable row level security;

create policy "Admin can read schedule notes" on public.schedule_slot_notes for select to authenticated using (public.is_admin());
create policy "Admin can insert schedule notes" on public.schedule_slot_notes for insert to authenticated with check (public.is_admin());
create policy "Admin can update schedule notes" on public.schedule_slot_notes for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "Admin can delete schedule notes" on public.schedule_slot_notes for delete to authenticated using (public.is_admin());
create policy "Public can read active promotions" on public.promotions for select to anon, authenticated using (active = true or public.is_admin());
create policy "Admin can insert promotions" on public.promotions for insert to authenticated with check (public.is_admin());
create policy "Admin can update promotions" on public.promotions for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "Admin can delete promotions" on public.promotions for delete to authenticated using (public.is_admin());

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('promotions', 'promotions', true, 6291456, array['image/jpeg','image/png','image/webp','image/gif'])
on conflict (id) do update set public = true, file_size_limit = 6291456,
  allowed_mime_types = array['image/jpeg','image/png','image/webp','image/gif'];
create policy "Public can view promotion images" on storage.objects for select to anon, authenticated using (bucket_id = 'promotions');
create policy "Admin can upload promotion images" on storage.objects for insert to authenticated with check (bucket_id = 'promotions' and public.is_admin());
create policy "Admin can update promotion images" on storage.objects for update to authenticated using (bucket_id = 'promotions' and public.is_admin());
create policy "Admin can delete promotion images" on storage.objects for delete to authenticated using (bucket_id = 'promotions' and public.is_admin());
